### ISSUE TITLE
Restart stopped components

### ISSUE THREAD

**Issue by redhog** [redhog/InfiniteGlass#43]
The result from `glass-action component restart glass-theme` is in... rolling drums...

```
59
Traceback (most recent call last):
  File "/InfiniteGlass/glass-lib/InfiniteGlass/display.py", line 30, in handle_x_event
    if handler(event):
  File "/InfiniteGlass/glass-lib/InfiniteGlass/display.py", line 101, in handler
    return fn(self, event)
  File "/InfiniteGlass/glass-lib/InfiniteGlass/window.py", line 72, in handler
    return fn(self, event)
  File "/InfiniteGlass/glass-ghosts/glass_ghosts/components.py", line 24, in PropertyNotify
    self.start_component(spec)
  File "/InfiniteGlass/glass-ghosts/glass_ghosts/components.py", line 63, in start_component
    del self.components_by_pid[pid]
KeyError: 59
```

**Comment by redhog** [comment]
Ah right... because glass-theme exits immediately after the initial zoom, and is never restarted.... But, an explicit restart _should_ start it even if it isn't running. That's a bug I guess...

**Comment by redhog** [comment]
Fixed in latest commit
